### ISSUE TITLE
Error when adding asset

### ISSUE THREAD

**Issue by b0b-ng** [LewisGauss/PapayaProject#13]
![image](https://user-images.githubusercontent.com/29788147/28002150-f6ce678e-6564-11e7-9788-e3304b9d29d0.png)

**Comment by b0b-ng** [comment]
All fields were completely filled including attaching photos

**Comment by LewisGauss** [comment]
Fixed. It was due to the database not knowing the tracking number counter.

**Comment by b0b-ng** [comment]
Error still persist
